"""initial_schema

Revision ID: 15642d764bc9
Revises: 
Create Date: 2026-09-07 18:58:10.118974
"""
import pgvector

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app

revision: str = '15642d764bc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('users',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('user_id', app.models.GUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', app.models.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('workspace_id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_channels_workspace_name')
    )
    op.create_table('files',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('channel_id', app.models.GUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('uploaded_by', app.models.GUID(), nullable=False),
    sa.Column('ingestion_status', sa.String(length=20), nullable=False),
    sa.Column('ingestion_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('user_id', app.models.GUID(), nullable=False),
    sa.Column('channel_id', app.models.GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_memberships_user_channel')
    )
    op.create_index('ix_memberships_channel_role', 'memberships', ['channel_id', 'role'], unique=False)
    op.create_index('ix_memberships_user_channel', 'memberships', ['user_id', 'channel_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('channel_id', app.models.GUID(), nullable=False),
    sa.Column('user_id', app.models.GUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_channel_created_at', 'messages', ['channel_id', 'created_at'], unique=False)
    op.create_table('chunks',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('file_id', app.models.GUID(), nullable=False),
    sa.Column('channel_id', app.models.GUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_channel_id', 'chunks', ['channel_id'], unique=False)
    op.create_index('ix_chunks_file_id', 'chunks', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_file_id', table_name='chunks')
    op.drop_index('ix_chunks_channel_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_messages_channel_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_memberships_user_channel', table_name='memberships')
    op.drop_index('ix_memberships_channel_role', table_name='memberships')
    op.drop_table('memberships')
    op.drop_table('files')
    op.drop_table('channels')
    op.drop_table('workspaces')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
